name: Build Android Release

on:
  workflow_dispatch:
  push:
    branches:
      - replit-agent
    paths:
      - 'android/**'
      - 'client/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.7'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build web app
        run: npm run build
        
      - name: Copy web build to Android assets
        run: |
          echo "Copying web build to android assets..."
          mkdir -p android/app/src/main/assets/public
          cp -r dist/public/* android/app/src/main/assets/public/
          
      - name: Make gradlew executable
        run: chmod +x android/gradlew
        
      - name: Build Android AAB
        working-directory: android
        run: ./gradlew bundleRelease --stacktrace --info
        
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-v1.0.87
          path: android/app/build/outputs/bundle/release/*.aab
          
      - name: Upload APK artifact (if exists)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug
          path: android/app/build/outputs/apk/**/*.apk
